languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- public/assets/**/*
- test/**/*
- "**/vendor/**/*"
- ".byebug_history"
- "app/assets/javascripts/jquery.ui.widget.js"
- db/**/*
